config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :artists
  resources :albums
  resources :tracks
end

app/models/album.rb
class Album < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_one_attached :cover_art_url
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_one_attached :avatar
end

app/models/track.rb
class Track < ApplicationRecord

  validates :name, presence: true

  has_one_attached :sound
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_action :set_album, only: [:edit, :update, :destroy, :show]

  def index
    @albums = Album.all
  end

  def show

  end

  def new 
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      flash[:notice] = "An album data was successfully created"
      redirect_to albums_path
    else
      flash[:error] = "There are some errors encountered"
      render :new
    end

  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to albums_path, notice: "An album data  was successfully updated"
    else
      flash[:error] = "There are some errors encountered"
      render :edit
    end
  end

  def destroy
    @album.destroy

    redirect_to albums_path, notice: "An album data was successfully destroyed"
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:name, :released, :released_at, :cover_art_url, :kind, :length)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:edit, :update, :destroy, :show]

  def index
    @artists = Artist.all
  end

  def show

  end

  def new 
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      flash[:notice] = "An artist data was successfully created"
      redirect_to artists_path
    else
      flash[:error] = "There are some errors encountered"
      render :new
    end

  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path, notice: "An artist data  was successfully updated"
    else
      flash[:error] = "There are some errors encountered"
      render :edit
    end
  end

  def destroy
    @artist.destroy

    redirect_to artists_path, notice: "An artist data was successfully destroyed"
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :permalink, :bio, :formed_at, :verified, :verified_at, :avatar_url, :cover_photo_url, :avatar)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :set_track, only: [:edit, :update, :destroy, :show]

  def index
    @tracks = Track.all
  end

  def show

  end

  def new 
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      flash[:notice] = "An track data was successfully created"
      redirect_to tracks_path
    else
      flash[:error] = "There are some errors encountered"
      render :new
    end

  end

  def edit
  end

  def update
    if @track.update(track_params)
      redirect_to tracks_path, notice: "An track data  was successfully updated"
    else
      flash[:error] = "There are some errors encountered"
      render :edit
    end
  end

  def destroy
    @track.destroy

    redirect_to tracks_path, notice: "An track data was successfully destroyed"
  end

  private

  def set_track
    @track = Track.find(params[:id])
  end

  def track_params
    params.require(:track).permit(:name, :url, :credits, :available, :sound)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.haml
%div{:class => "text-gray-400 border-separate space-y-6 text-sm"}
  = form_with model: @album do |a|
    - if @album.errors.any?
      %h2{:class => "text-red-600"} Errors: 
      %ul{:class => "text-red-600"}
        - @album.errors.full_messages.each do |message|
          %li= message
    = a.label :name
    = a.text_field :name, :class => "m-0 h-6"
    %br/
    = a.label :released
    = a.check_box :released, :class => "m-0 h-4"
    %br/
    = a.label :released_at
    = a.text_field :released_at, :class => "m-0 h-6"
    %br/
    = a.label :cover_art_url
    -# = a.text_field :cover_art_url
    = a.file_field :cover_art_url
    %br/
    = a.label :length
    = a.text_field :length, :class => "m-0 h-6"
    %br/
    = a.label :kind
    = a.radio_button :kind, 'EP'
    = a.label :kind, 'EP', :value => 'EP'
    = a.radio_button :kind, 'LP'
    = a.label :kind, 'LP', :value => 'LP'
    = a.radio_button :kind, 'Single'
    = a.label :kind, 'Single', :value => 'Single'
    %br/
    = a.submit 'Create Album Data', :class => "p-2 bg-gray-500 text-gray-100 cursor-pointer"

  %br/
  %button{:class => "p-2 pl-5 pr-5 bg-gray-500 text-gray-100 text-lg rounded-lg focus:border-4 border-gray-300"}
    = link_to albums_path do
      Back to index


app/views/albums/edit.html.haml
%h1{:class => "text-gray-400 m-6"}
  Edit the Album data

= render 'form'

app/views/albums/index.html.haml
%table{:class => "table text-gray-400 border-separate space-y-6 text-sm"}
  %thead{:class => "bg-gray-800 text-gray-500"}
    %tr
      %th{:class => "p-3"} Name
      %th{:class => "p-3 text-left"} Released
      %th{:class => "p-3 text-left"} Released At
      %th{:class => "p-3 text-left"} Cover Art Url
      %th{:class => "p-3 text-left"} Length
      %th{:class => "p-3 text-left"} Kind
      %th{:class => "text-center"} Action
  %tbody
    - @albums.each do |album|
      %tr{:class => "bg-gray-800"}
        %td{:class => "p-3"}= album.name
        %td{:class => "p-3"}
          - if album.released
            ="Yes"
          - else
            ="No"
        %td{:class => "p-3"}= album.released_at
        -# %td{:class => "p-3 max-w-xs"}
        -#   %img{ src: "#{album.cover_art_url}" }
        %td{:class => "p-3 max-w-xs"}
          - if album.cover_art_url.attached?
            = image_tag album.cover_art_url, width: "200px"
        %td{:class => "p-3"}= album.length
        %td{:class => "p-3"}= album.kind
        %td{:class => "p-3"}
          %div{:class => "flex flex-row text-gray-400 mx-2"}
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to 'visibility', album, class: "material-icons-outlined text-base"
            |
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to edit_album_path(album.id) do
                %i.material-icons-outlined.text-base edit
            |
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to album_path(album.id), method: :delete, data: { confirm: "Are you sure?" } do
                %i.material-icons-round.text-base delete_outline
%br/
%br/
%button{:class => "p-2 pl-5 pr-5 bg-gray-500 text-gray-100 text-lg rounded-lg focus:border-4 border-gray-300"}
  = link_to new_album_path do
    New Album Data

app/views/albums/new.html.haml
%h1{:class => "text-gray-400 m-6"}
  Create the Album data

= render 'form'

app/views/albums/show.html.haml
%div{:class => "grid justify-items-center mx-96 text-gray-400 border-separate space-y-6 text-sm"}
  %p
    %strong Name:
    = @album.name
  %p
    %strong Released:
    - if @album.released
      ="Yes"
    - else
      ="No"
  %p
    %strong Released at:
    = @album.released_at
  -# %p
  -#   %strong Cover Art:
  -#   %div{:class => "p-3 max-w-xs"}
  -#     %img{ src: "#{@album.cover_art_url}" }
  - if @album.cover_art_url.attached?
    %p
      %strong Avatar:
      %div{:class => "p-3 max-w-xs"}
        = image_tag @album.cover_art_url, width: "200px"
  %p
    %strong Length:
    = @album.length
  %p
    %strong Kind:
    = @album.kind

  = link_to 'Edit', edit_album_path(@album)
  = link_to 'Back', albums_path

app/views/artists/_form.html.haml
%div{:class => "text-gray-400 border-separate space-y-6 text-sm"}
  = form_with model: @artist do |f|
    - if @artist.errors.any?
      %h2{:class => "text-red-600"} Errors: 
      %ul{:class => "text-red-600"}
        - @artist.errors.full_messages.each do |message|
          %li= message
    = f.label :name
    = f.text_field :name, :class => "m-0 h-6"
    %br/
    = f.label :permalink
    = f.text_field :permalink, :class => "m-0 h-6"
    %br/
    = f.label :bio
    = f.text_area :bio
    = if f.object.errors[:bio].present?
      %span
      = f.object_error[:bio].to_sentence
    %br/
    = f.label :formed_at
    = f.text_field :formed_at, :class => "m-0 h-6"
    %br/
    = f.label :verified
    = f.check_box :verified, :class => "m-0 h-4"
    %br/
    = f.label :verified_at
    = f.text_field :verified_at, :class => "m-0 h-6"
    %br/
    -# = f.label :avatar_url
    -# = f.text_field :avatar_url, :class => "m-0 h-6"
    -# %br/
    = f.label :avatar
    = f.file_field :avatar
    %br/
    = f.label :cover_photo_url
    = f.text_field :cover_photo_url, :class => "m-0 h-6"
    %br/
    = f.submit 'Create Artist Data', :class => "p-2 bg-gray-500 text-gray-100 cursor-pointer"

    -# %input{class: "bg-gray-900 text-white pl-10 pr-4 py-2 rounded-lg w-full",
    -#     sm: "bg-red-400 pl-2",
    -#     focus: "outline-none bg-white text-gray-900",
    -#     hover: "outline-none bg-white text-gray-900",
    -#     placeholder: "Search by keywords"}
  %br/
  %button{:class => "p-2 pl-5 pr-5 bg-gray-500 text-gray-100 text-lg rounded-lg focus:border-4 border-gray-300"}
    = link_to artists_path do
      Back to index


app/views/artists/edit.html.haml
%h1 Edit the Artist data 

= render 'form'

app/views/artists/index.html.haml
-# %p This is coming from artists#index
-# %br/
-# %br/

%table{:class => "table text-gray-400 border-separate space-y-6 text-sm"}
  %thead{:class => "bg-gray-800 text-gray-500"}
    %tr
      %th{:class => "p-3"} Name
      %th{:class => "p-3 text-left"} Permalink
      %th{:class => "p-3 text-left w-60"} Bio
      %th{:class => "p-3 text-left"} Formed at
      %th{:class => "p-3 text-left"} Verified?
      %th{:class => "p-3 text-left"} Verified_at
      %th{:class => "p-3 text-center"} Avatar
      %th{:class => "p-3 text-center"} Cover Photo
      %th{:class => "text-center"} Action
      -# %th Avatar
  %tbody
    - @artists.each do |artist|
      %tr{:class => "bg-gray-800"}
        %td{:class => "p-3"}= artist.name
        %td{:class => "p-3"}= artist.name.downcase.split(" ").join("-")
        %td{:class => "p-3 w-60"}= artist.bio.truncate(150)
        %td{:class => "p-3"}= artist.formed_at
        %td{:class => "p-3"}
          - if artist.verified
            ="Yes"
          - else
            ="No"
        %td{:class => "p-3"}= artist.verified_at
        -# %td{:class => "p-3 max-w-xs"}
        -#   %img{ src: "#{artist.avatar_url}" }
        %td{:class => "p-3 max-w-xs"}
          - if artist.avatar.attached?
            = image_tag artist.avatar, width: "200px"
        %td{:class => "p-3 max-w-xs"}
          %img{ src: "#{artist.cover_photo_url}" }
        %td{:class => "p-3"}
          %div{:class => "flex flex-row text-gray-400 mx-2"}
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to 'visibility', artist, class: "material-icons-outlined text-base" 
            |
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to edit_artist_path(artist.id) do
                %i.material-icons-outlined.text-base edit
            |
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to artist_path(artist.id), method: :delete, data: { confirm: "Are you sure?" } do
                %i.material-icons-round.text-base delete_outline
%br/
%br/
%button{:class => "p-2 pl-5 pr-5 bg-gray-500 text-gray-100 text-lg rounded-lg focus:border-4 border-gray-300"}
  = link_to new_artist_path do
    New Artist Data

app/views/artists/new.html.haml
%h1{:class => "text-gray-400 m-6"}
  Create the Artist data

= render 'form'

app/views/artists/show.html.haml
%div{:class => "grid justify-items-center mx-96 text-gray-400 border-separate space-y-6 text-sm"}
  %p
    %strong Name:
    = @artist.name
  %p
    %strong Permalink:
    = @artist.permalink
  %p
    %strong Formed at:
    = @artist.formed_at
  %p
    %strong Bio:
    = @artist.bio
  %p
    %strong Verified:
    - if @artist.verified
      ="Yes"
    - else
      ="No"
  %p
    %strong Verified at:
    = @artist.verified_at
  -# %p
  -#   %strong Avatar:
  -#   %div{:class => "p-3 max-w-xs"}
  -#     %img{ src: "#{@artist.avatar_url}" }
  - if @artist.avatar.attached?
    %p
      %strong Avatar:
      %div{:class => "p-3 max-w-xs"}
        = image_tag @artist.avatar, width: "200px"
  %p
    %strong Cover Photo:
    %div{:class => "p-3 max-w-xs"}
      %img{ src: "#{@artist.cover_photo_url}" }

  = link_to 'Edit', edit_artist_path(@artist)
  = link_to 'Back', artists_path


-# -if @artist.cover_photo.attached?
-#   %p
-#     %strong Cover photo:
-#     = image_tag @artist.cover_photo, width: '200px'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link
    href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
    rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
  </head>

  <body>
    <div class="nav-bar bg-gray-700 text-gray-100">
      <div class="nav-links">
        <div class="nav-link">
          <%= link_to "Artists", artists_path %>
        </div>
        <div class="nav-link">
          <%= link_to "Albums", albums_path %>
        </div>
        <div class="nav-link">
          <%= link_to "Tracks", tracks_path %>
        </div>
      </div>
    </div>

    <div class="flex items-center justify-center min-h-screen bg-gray-900">
      <div class="col-span-12">
        <div class="overflow-auto lg:overflow-visible text-gray-400">
          <%= flash[:notice] %>
          <%= flash[:errors] %>
          <%= yield %>
          
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tracks/_form.html.haml
%div{:class => "text-gray-400 border-separate space-y-6 text-sm"}
  = form_with model: @track do |t|
    - if @track.errors.any?
      %h2{:class => "text-red-600"} Errors: 
      %ul{:class => "text-red-600"}
        - @track.errors.full_messages.each do |message|
          %li= message
    = t.label :name
    = t.text_field :name, :class => "m-0 h-6"
    %br/
    = t.label :url
    = t.text_field :url, :class => "m-0 h-6"
    %br/
    = t.label :credits
    = t.text_field :credits, :class => "m-0 h-6"
    %br/
    = t.label :available
    = t.check_box :available, :class => "m-0 h-4"
    %br
    =t.label :sound
    =t.file_field :sound, direct_upload: true
    %br/
    = t.submit 'Create Track Data', :class => "p-2 bg-gray-500 text-gray-100 cursor-pointer"

  %br/
  %button{:class => "p-2 pl-5 pr-5 bg-gray-500 text-gray-100 text-lg rounded-lg focus:border-4 border-gray-300"}
    = link_to tracks_path do
      Back to index


app/views/tracks/edit.html.haml
%h1{:class => "text-gray-400 m-6"}
  Edit the Track data

= render 'form'

app/views/tracks/index.html.haml
%table{:class => "table text-gray-400 border-separate space-y-6 text-sm"}
  %thead{:class => "bg-gray-800 text-gray-500"}
    %tr
      %th{:class => "p-3"} Name
      %th{:class => "p-3 text-left"} Url
      %th{:class => "p-3 text-left"} Credits
      %th{:class => "p-3 text-left"} Available
      %th{:class => "p-3 text-center"} Music Play
      %th{:class => "text-center"} Action
  %tbody
    - @tracks.each do |track|
      %tr{:class => "bg-gray-800"}
        %td{:class => "p-3"}= track.name
        %td{:class => "p-3"}= track.url
        %td{:class => "p-3"}= track.credits
        %td{:class => "p-3"}
          - if track.available
            ="Yes"
          - else
            ="No"
        %td= audio_tag(rails_blob_url(track.sound), controls: "controls", type: "track.sound.content_type") if track.sound.audio?
        %td{:class => "p-3"}
          %div{:class => "flex flex-row text-gray-400 mx-2"}
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to 'visibility', track, class: "material-icons-outlined text-base"
            |
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to edit_track_path(track.id) do
                %i.material-icons-outlined.text-base edit
            |
            %div{:class => "hover:text-gray-100 px-1"}
              = link_to track_path(track.id), method: :delete, data: { confirm: "Are you sure?" } do
                %i.material-icons-round.text-base delete_outline
%br/
%br/
%button{:class => "p-2 pl-5 pr-5 bg-gray-500 text-gray-100 text-lg rounded-lg focus:border-4 border-gray-300"}
  = link_to new_track_path do
    New Track Data

app/views/tracks/new.html.haml
%h1{:class => "text-gray-400 m-6"}
  Create the Track data

= render 'form'

app/views/tracks/show.html.haml
%div{:class => "grid justify-items-center mx-96 text-gray-400 border-separate space-y-6 text-sm"}
  %p
    %strong Name:
    = @track.name
  %p
    %strong Url:
    = @track.url
  %p
    %strong Credits:
    = @track.credits
  %p
    %strong Available:
    - if @track.available
      ="Yes"
    - else
      ="No"
  %p
    = audio_tag(rails_blob_url(@track.sound), controls: "controls", type: "track.sound.content_type") if @track.sound.audio?

  = link_to 'Edit', edit_track_path(@track)
  = link_to 'Back', tracks_path